---
- name: Java
  debug:
    msg: "Installing openjdk v8 for distribution {{ ansible_facts['distribution'] }}"

- name: install openjdk-8-jre-headless (apt)
  apt:
    name: openjdk-8-jre-headless
    state: present
    update_cache: yes
  become: yes
  when: (ansible_facts['os_family'] == "Debian")

- name: install java-1.8.0-openjdk-headless (yum)
  yum:
    name: java-1.8.0-openjdk-headless
    state: present
    update_cache: yes
  become: yes
  when: (ansible_facts['os_family'] == "RedHat")
